# Generated by Django 3.2.18 on 2023-08-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0012_delete_signprotinteractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signprotstructureextraproteins',
            name='protein_conformation',
        ),
    ]
