# Generated by Django 3.2.18 on 2024-02-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0025_auto_20230831_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligandpeptidestructure',
            name='model',
        ),
    ]
