# Generated by Django 3.2.25 on 2025-01-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0027_auto_20241204_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
