# Generated by Django 3.2.25 on 2025-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0028_ligand_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='source',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
