# Generated by Django 3.2.25 on 2025-02-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0029_alter_ligand_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ligand.ligand'),
        ),
    ]
