# Generated by Django 3.2.25 on 2025-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0030_ligand_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='clean_inchikey',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
