# Generated by Django 3.2.25 on 2025-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0031_auto_20250310_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandrole',
            name='effect',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligandrole',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
