# Generated by Django 3.2.25 on 2025-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0032_auto_20250423_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='helm',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
