# Generated by Django 3.2.25 on 2025-05-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20250318_1242'),
        ('ligand', '0033_ligand_helm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigandTargetPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandeffect')),
                ('ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandtype')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
        migrations.AlterField(
            model_name='ligandrole',
            name='effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandeffect'),
        ),
    ]
