# Generated by Django 3.2.25 on 2025-06-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
        ('ligand', '0034_auto_20250514_1404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligandid',
            unique_together={('ligand', 'index', 'web_resource')},
        ),
    ]
