# Generated by Django 3.2.25 on 2025-08-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0035_alter_ligandid_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='qualitative_activity',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='helm',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
