# Generated by Django 3.2.18 on 2023-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0016_auto_20230216_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactingpeptideresiduepair',
            name='ca_cb_ca_angle',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='interactingpeptideresiduepair',
            name='ca_distance',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
