# Generated by Django 3.2.18 on 2023-12-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0018_auto_20231201_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactingpeptideresiduepair',
            old_name='ca_cb_ca_angle',
            new_name='ca_cb_angle',
        ),
    ]
