# Generated by Django 3.2.18 on 2024-02-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0019_rename_ca_cb_ca_angle_interactingpeptideresiduepair_ca_cb_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactingpeptideresiduepair',
            name='ca_cb_angle',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interactingpeptideresiduepair',
            name='ca_distance',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
