# Generated by Django 3.2.18 on 2023-05-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('protein', '0016_auto_20220225_1650'),
        ('common', '0006_releasestatistics_database'),
        ('structure', '0042_auto_20220916_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRMSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateField(null=True)),
                ('seq_id', models.IntegerField(null=True)),
                ('seq_sim', models.IntegerField(null=True)),
                ('overall_all', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('overall_backbone', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('TM_all', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('TM_backbone', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('H8', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ICL1', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ECL1', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ICL2', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ECL2', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ECL3', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('binding_pocket', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('notes', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'structure_rmsd',
            },
        ),
        migrations.RenameModel(
            old_name='StructureModelpLDDT',
            new_name='StructurepLDDT',
        ),
        migrations.RemoveField(
            model_name='structuremodelrmsd',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelrmsd',
            name='main_template',
        ),
        migrations.RemoveField(
            model_name='structuremodelrmsd',
            name='target_structure',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='protein_conformation',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='stats_text',
        ),
        migrations.AddField(
            model_name='structure',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='pdb_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='pdb_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='resolution',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='structureplddt',
            name='structure_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
        migrations.AlterField(
            model_name='structuretype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterModelTable(
            name='structureplddt',
            table='structure_plddt',
        ),
        migrations.DeleteModel(
            name='StructureModel',
        ),
        migrations.DeleteModel(
            name='StructureModelRMSD',
        ),
        migrations.AddField(
            model_name='structurermsd',
            name='homology_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
        migrations.AddField(
            model_name='structurermsd',
            name='target_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_structure', to='structure.structure'),
        ),
    ]
