# Generated by Django 3.2.18 on 2023-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0017_auto_20230814_1042'),
        ('structure', '0043_auto_20230523_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureextraproteins',
            name='protein_conformation',
        ),
        migrations.AddField(
            model_name='structure',
            name='stats_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.statstext'),
        ),
        migrations.AddField(
            model_name='structureextraproteins',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_protein', to='protein.protein'),
        ),
        migrations.AlterField(
            model_name='structureextraproteins',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex_protein', to='structure.structure'),
        ),
        migrations.AlterField(
            model_name='structureextraproteins',
            name='wt_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wt_protein', to='protein.protein'),
        ),
        migrations.DeleteModel(
            name='StructureComplexModel',
        ),
    ]
