# Generated by Django 2.2.17 on 2026-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0049_structuremodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureModelStatisticsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_entry_name', models.CharField(max_length=20)),
                ('uniprot_accession', models.CharField(max_length=20)),
                ('protein_name', models.CharField(max_length=100)),
                ('receptor_family', models.CharField(max_length=100, null=True)),
                ('receptor_class', models.CharField(max_length=100, null=True)),
                ('gene_name', models.CharField(max_length=100, null=True)),
                ('gene_entrez_id', models.CharField(max_length=100, null=True)),
                ('species_common_name', models.CharField(max_length=100, null=True)),
                ('st_inact_c', models.IntegerField()),
                ('st_interm_c', models.IntegerField()),
                ('st_act_c', models.IntegerField()),
                ('best_res_inact', models.FloatField(null=True)),
                ('best_res_interm', models.FloatField(null=True)),
                ('best_res_act', models.FloatField(null=True)),
                ('transd_gio_c', models.IntegerField()),
                ('transd_gq11_c', models.IntegerField()),
                ('transd_g1213_c', models.IntegerField()),
                ('transd_arrest_c', models.IntegerField()),
                ('transd_grks_c', models.IntegerField()),
                ('ligand_types_smmol_c', models.IntegerField()),
                ('ligand_types_pep_c', models.IntegerField()),
                ('limodgrp_stim_c', models.IntegerField()),
                ('limodgrp_inhib_c', models.IntegerField()),
                ('limodgrp_unk_c', models.IntegerField()),
                ('limod_apo_c', models.IntegerField()),
                ('limod_ag_c', models.IntegerField()),
                ('limod_ag_partial_c', models.IntegerField()),
                ('limod_allo_antag_c', models.IntegerField()),
                ('limod_antag_c', models.IntegerField()),
                ('limod_inv_ag_c', models.IntegerField()),
                ('limod_nam_c', models.IntegerField()),
                ('limod_pam_c', models.IntegerField()),
                ('limod_unk_c', models.IntegerField()),
            ],
            options={
                'db_table': 'structure_model_statistics',
            },
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['uniprot_entry_name'], name='uniprot_entry_name_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['protein_name'], name='protein_name_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['receptor_family'], name='receptor_family_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['receptor_class'], name='receptor_class_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['gene_name'], name='gene_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['species_common_name'], name='species_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['st_inact_c'], name='st_inact_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['st_interm_c'], name='st_interm_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['st_act_c'], name='st_act_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['best_res_inact'], name='best_res_inact_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['best_res_interm'], name='best_res_interm_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['best_res_act'], name='best_res_act_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['transd_gio_c'], name='transd_gio_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['transd_gq11_c'], name='transd_gq11_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['transd_g1213_c'], name='transd_g1213_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['transd_arrest_c'], name='transd_arrest_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['transd_grks_c'], name='transd_grks_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['ligand_types_smmol_c'], name='ligand_types_smmol_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['ligand_types_pep_c'], name='ligand_types_pep_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limodgrp_stim_c'], name='limodgrp_stim_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limodgrp_inhib_c'], name='limodgrp_inhib_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limodgrp_unk_c'], name='limodgrp_unk_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_apo_c'], name='limod_apo_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_ag_c'], name='limod_ag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_ag_partial_c'], name='limod_ag_partial_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_allo_antag_c'], name='limod_allo_antag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_antag_c'], name='limod_antag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_inv_ag_c'], name='limod_inv_ag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_nam_c'], name='limod_nam_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_pam_c'], name='limod_pam_c_idx'),
        ),
        migrations.AddIndex(
            model_name='structuremodelstatisticstable',
            index=models.Index(fields=['limod_unk_c'], name='limod_unk_c_idx'),
        ),
    ]
