# Generated by Django 3.2.18 on 2023-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0017_auto_20230814_1042'),
        ('residue', '0002_auto_20180504_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='protein_conformation',
        ),
        migrations.AddField(
            model_name='residue',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein'),
        ),
    ]
