# Generated by Django 3.2.18 on 2023-08-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0019_auto_20230818_1009'),
        ('residue', '0003_auto_20230814_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein'),
        ),
    ]
