# Generated by Django 3.2.18 on 2023-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0016_auto_20220225_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinTemplateStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'protein_template_structure',
            },
        ),
        migrations.RemoveField(
            model_name='proteinconformation',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='proteinconformation',
            name='protein_anomalies',
        ),
        migrations.RemoveField(
            model_name='proteinconformation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='proteinconformationtemplatestructure',
            name='protein_conformation',
        ),
        migrations.RemoveField(
            model_name='proteinconformationtemplatestructure',
            name='protein_segment',
        ),
        migrations.RemoveField(
            model_name='proteinconformationtemplatestructure',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='identifiedsites',
            name='protein_conformation',
        ),
        migrations.AddField(
            model_name='identifiedsites',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_protein', to='protein.protein'),
        ),
        migrations.RemoveField(
            model_name='protein',
            name='states',
        ),
        migrations.AddField(
            model_name='protein',
            name='states',
            field=models.ManyToManyField(to='protein.ProteinState'),
        ),
    ]
