# Generated by Django 3.2.18 on 2023-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0044_auto_20230814_1042'),
        ('residue', '0003_auto_20230814_1042'),
        ('signprot', '0013_remove_signprotstructureextraproteins_protein_conformation'),
        ('protein', '0017_auto_20230814_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProteinConformation',
        ),
        migrations.DeleteModel(
            name='ProteinConformationTemplateStructure',
        ),
        migrations.AddField(
            model_name='proteintemplatestructure',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein'),
        ),
        migrations.AddField(
            model_name='proteintemplatestructure',
            name='protein_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsegment'),
        ),
        migrations.AddField(
            model_name='proteintemplatestructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
