# Generated by Django 3.2.18 on 2023-08-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20230814_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='states',
        ),
        migrations.AddField(
            model_name='protein',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate'),
        ),
    ]
