# Generated by Django 2.2.17 on 2026-02-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20250828_1656'),
        ('protein', '0020_auto_20250318_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='entrez_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='entrez_weblink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink'),
        ),
    ]
